# Remove any languages you don't want analyzed.
languages:
   Ruby: true
   JavaScript: true
   Python: true
# For all languages, we support a standard set of Glob patterns.
exclude_paths:
 - angular.js # Exclude a specific file
 - bower_components/*.js 
# - app/controllers/*.py # Exclude specific files type within a folder/subfolders
# - lib/**/*.rb # Recursively ignore all files ending in .rb
